name: Docs

on:
  push:
    branches:
      - develop

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://npm.pkg.github.com/
          scope: '@psychedelic'
      - run: npm install
      - run: npm run prepare
      - run: npm run docs
      - run: |
            git config --global user.name "${{ secrets.GH_USER }}"
            git config --global user.email "${{ secrets.GH_MAIL }}"

            git add docs git commit -m "chore: update docs"
            git push
